import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Table from './lib/Table';

export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>Test</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Table />
		</div>
	);
}
